### ISSUE TITLE
Go to definition doesn't work

### ISSUE THREAD

**Issue by shanewazabbas** [nickjmiller/pytest-fixtures#14]
If I click go to definition on the fixture it just goes to where the fixture is actually being used. Also there are logs indicating the full path to opening files is wrong:

```
[6/2/2022 - 1:50:15 PM] Unable to read file at path /Users/XXXX/Tests/Tests/integration/conftest.py, Error: ENOENT: no such file or directory, open '/Users/XXXX/Tests/Tests/integration/conftest.py'
```

The path should be: `'/Users/XXXX/Tests/integration/conftest.py'` Maybe this is related the issue.

There are also logs saying it found fixtures. I'm not sure what is going on here. 

Maybe some settings need to be opened up so we can configure file paths ourselves. Not sure.

**Comment by nickjmiller** [comment]
Can you provide the output of `pytest --fixtures -v /path/to/file` for the file where you are experiencing the issue?

**Comment by nickjmiller** [comment]
The file path is parsed from the output of that command, if you paste it I may be able to understand what caused this issue.

**Comment by shanewazabbas** [comment]
Sure, here's an example:
```
jwks [session scope] -- Tests/integration/conftest.py:275
    no docstring available
```

**Comment by shanewazabbas** [comment]
I do not see a `rootDir` line:

```
[6/3/2022 - 11:48:46 AM] Changed active file to /Users/XXXX/Tests/integration/conftest.py, loading fixtures...
[6/3/2022 - 11:48:46 AM] File is a python test file, loading fixtures...
[6/3/2022 - 11:48:46 AM] Running command /Users/XXX/.pyenv/versions/3.8.0/bin/python -m pytest --color no --fixtures -v /Users/XXXX/Tests/integration/conftest.py in directory /Users/XXXX
[6/3/2022 - 11:48:51 AM] Unable to read file at path /Users/XXXX/Tests/Tests/conftest.py, Error: ENOENT: no such file or directory, open '/Users/XXXX/Tests/Tests/conftest.py'

```

Ran the command from the output and i get a whole bunch of fixtures spit out. Same as before:
```
jwks [session scope] -- Tests/integration/conftest.py:275
    no docstring available
```

**Comment by shanewazabbas** [comment]
Ah i see what you mean. 

Found it:
`rootdir: /Users/XXXX/project/Tests, configfile: pytest.ini`

**Comment by nickjmiller** [comment]
Okay so it looks like your rootdir contains `/Tests`, and the fixture path also include `/Tests`. I'm not sure why you are seeing that behavior, but that is the issue. I can add some logic to merge the directories when concatenating the paths, which could potentially break someone else who happens to have two directories with the same name, but I think that's a low risk. I'll work on this later today.

**Comment by shanewazabbas** [comment]
I think another option is having a rootDir option in the settings json file. Where I can specify it to be:
```
"rootDir": "/Users/XXXX/project"
```

and that can take precedence if set when extension is doing its thing. But its totally up to you what is best to implement.

**Comment by nickjmiller** [comment]
That is a good idea but might get complicated with multi-root workspaces. I am wondering how your pytest.ini file might be interacting with this, can I ask you to run the fixtures with two different parameters and see if those directories and paths change in the output?

The first parameter, can you add `rootdir=.` to the command?

Secondly, can you run it again with `-c /dev/null`?

And let me know if either of these change the rootdir or the path to the fixtures?

**Comment by nickjmiller** [comment]
Feel free to reopen, please include the details above

**Comment by anentropic** [comment]
I have similar problem

If I look at the log output from pytest-fixtures I see a lot of:

> [10/27/2022 - 4:17:35 PM] Unable to read file at path /Users/anentropic/Documents/Dev/myproject/platform/src/subproj1/platform/src/subproj1/tests/conftest.py, Error: ENOENT: no such file or directory, open '/Users/anentropic/Documents/Dev/myproject/platform/src/subproj1/platform/src/subproj1/tests/conftest.py'


My workspace root is `/Users/anentropic/Documents/Dev/myproject/`  but I have sub projects under `platform/src/`

What seems to be wrong is that part of the path is repeated `/platform/src/subproj1/platform/src/subproj1/`

I decided to create a `myproj.code-workspace` file and add the subprojects as `folders`. This causes the files in the root of the monorepo to disappear, leaving only the subproject folders, but I can live with that for now.

If I go back and try again the pytest-fixtures logs show:

> [10/27/2022 - 4:31:30 PM] Running command /Users/anentropic/Library/Caches/pypoetry/virtualenvs/subproj3-pL3y38LY-py3.10/bin/python -m pytest --color no --fixtures -v /Users/anentropic/Documents/Dev/myproject/platform/src/subproj3/tests/my_test_file.py in directory /Users/anentropic/Documents/Dev/myproject/platform/src/subproj1
[10/27/2022 - 4:31:31 PM] Found 52 fixtures

This is better now - it found fixtures instead of "no such file" errors. It's weird that the "in directory" points to the first subproj in my workspace `folders`, rather than the current one.

It didn't navigate directly to the fixture def when I click on a fixture arg in a testcase, but it _does_ open up the inline "Definitions" view... This lists 2 definitions, one of which is just the arg to the test case (not useful) and the other is the correct location of the fixture definition within the correct subproject.
