### ISSUE TITLE
Some integration tests not pass

### ISSUE THREAD

**Issue by thu2004** [nickjmiller/pytest-fixtures#26]
When I run the integration tests, some of the tests not passing. The cause is the sandbox environments python3 does not have pytest installed.

@nickjmiller Can you please verify ?

**Comment by nickjmiller** [comment]
When you say integration tests what are you refering to? How are you executing them and can you paste the output?

**Comment by thu2004** [comment]
By call "npm test"


Error: 12 tests failed.
        at /home/ctule/study/pytest-fixtures/out/test/suite/index.js:25:32
        at done (/home/ctule/study/pytest-fixtures/node_modules/mocha/lib/mocha.js:1068:7)

[main 2022-09-24T01:14:20.443Z] Waiting for extension host with pid 29233 to exit.

[main 2022-09-24T01:14:20.475Z] Extension host with pid 29233 exited with code: 0, signal: null.

Exit code:   1
Done

Failed to run tests
npm ERR! Test failed.  See above for more details.

**Comment by nickjmiller** [comment]
It's best to run the tests using the "Extension Tests" launch configuration [see here for info](https://code.visualstudio.com/docs/editor/debugging#_launch-configurations), I've noticed they can be flakey otherwise. You should see test output in the `Debug Console` tab. I do think the tests would fail if you don't have python installed on your system, though.

**Comment by thu2004** [comment]
Yes, the python and pytest must be installed. I add a check for pytest as precondition to run tests.
https://github.com/nickjmiller/pytest-fixtures/pull/27
